package com.prgrms.ohouse.domain.community.model.housewarming;

public enum WorkTarget {
	FOLDING_DOOR, KITCHEN_RENOVATION, BATHROOM_RENOVATION, ART_WALL, LIGHT_INSTALLATION,
	EXPANSION_OF_BALCONY, INNER_DOOR, SLIDING_DOOR, FAKE_WALL_AND_DIVIDER
}
